version: '3.8'

services:
  app:
    build:
      context: .
    container_name: laravel_app
    restart: unless-stopped
    ports:
      - "8000:8000"  # Correct port mapping for the app
    environment:
      - APP_NAME=Music
      - APP_ENV=local
      - APP_KEY=base64:GfSrJ9ptnWux+iRyT1Y+7ABvrLjQgOxpGsFSSss4p7s=
      - APP_DEBUG=true
      - APP_URL=http://localhost
      - APP_LOCALE=en
      - APP_FALLBACK_LOCALE=en
      - APP_FAKER_LOCALE=en_US
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=migmag_db
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - MAIL_MAILER=smtp
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USERNAME=shifatghi@gmail.com
      - MAIL_PASSWORD=zugbluhvvpekmftc
      - MAIL_ENCRYPTION=tls
      - MAIL_FROM_ADDRESS="shifatghi@gmail.com"
      - MAIL_FROM_NAME=Music
      - STRIPE_SECRET=sk_test_51RLzucIC4wM63k4fAxSuxFdVpSwosqueLS0CRZCRnH0tUsMsAorccPHwCfjUHixtGczni9wAUK8ZLLkjo6UgeNJV00bXiI9TMn
    volumes:
      - .:/var/www
    networks:
      - laravel-network

  db:
    image: mysql:5.7
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: migmag_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"  # Correct port mapping for the DB (change host port to 3307)
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel-network

volumes:
  db_data:

networks:
  laravel-network:
    driver: bridge
